FirebaseOptions: move default initialization from Builder
firebase/firebase-admin-java pull request #592
Opened 2021-08-30 14:14 UTC by amarkevich

Use provided by Builder objects prior to init defaults.
Avoid `ClassNotFoundException` when JacksonFactory excluded
```
                FirebaseOptions.builder()
                    .setJsonFactory(Utils.getDefaultJsonFactory())
                    .build()
``````
        <dependency>
            <groupId>com.google.firebase</groupId>
            <artifactId>firebase-admin</artifactId>
            <exclusions>
                <exclusion>
                    <groupId>com.google.http-client</groupId>
                    <artifactId>google-http-client-jackson2</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
```

2021-08-30 14:23 UTC, amarkevich commented
@googlebot I fixed it.

2021-08-30 14:26 UTC, amarkevich commented
@googlebot I fixed it.

2021-08-30 20:17 UTC, hiranya911 requested changes
Thanks for the PR. This looks like a good improvement to have. I've suggested some changes.

2021-08-31 06:41 UTC, amarkevich commented on src/test/java/com/google/firebase/FirebaseOptionsTest.java
> -  @Test(expected = NullPointerException.class)
@hiranya911 p.1 implemented

2021-08-31 20:03 UTC, merged